### ISSUE TITLE
not able to sort fonts correctly

### ISSUE THREAD

**Issue by anuragphadke** [yunusga/postcss-sort-media-queries#30]
Hi,
I am sorting the CSS at https://beta.webfast.co/webfives-com/main.css as `mobile-first`.
However, the fonts seem to be bit whacky after the sort.

Scroll to the section that says "Make your mobile website load under a second"

Before: https://beta.webfast.co/webfives-com/before.html (uses Proxima font)
After: https://beta.webfast.co/webfives-com/after.html (uses Graphik font)

**Question 1**: Is there a way to retain the order of CSS that is not included as part of @media query? If I copy the CSS that's not part of `@media query` to the bottom (CSS specificity maybe?), the page renders w/o any issues.

**Question 2**: Do I need a custom sort algorithm here?

**Comment by yunusga** [comment]
Hi, you problem is Graphik insted Proxima after sorting?

**Comment by anuragphadke** [comment]
Yup, that's correct. 
There are also other CSS rules whose position and thereby priority gets flipped once I run the sort..

**Comment by yunusga** [comment]
In this case, you need to specify the rules correctly, because sorting MQ does not affect the usual rules in any way, but only groups similar ones, moves them down and sorts. Which reveals the specificity of rules without MQ standing before or after them before sorting. Custom sort algorithm won't help.

**Comment by anuragphadke** [comment]
Got it. Thanks for the quick reply!
